- name: Aggiornamento completo del sistema Linux
  hosts: all
  ignore_unreachable: true
  ignore_errors: "{{ ansible_check_mode }}"
  become: yes
  gather_facts: false   # ← non necessario, li conosci già
  vars:
    ansible_ssh_timeout: 5
  tasks:
    - name: Aggiorna la cache dei pacchetti ed esegui l'upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        purge: yes


