- name: Aggiornamento completo del sistema Linux
  hosts: all
  ignore_unreachable: true
  become: yes
  gather_facts: false   # ← non necessario, li conosci già
  vars:
    ansible_ssh_timeout: 5
  tasks:
    - name: Aggiorna la cache dei pacchetti ed esegui l'upgrade
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        purge: yes

    - name: Controlla se è richiesto un riavvio
      register: reboot_required_file
      stat:
        path: /var/run/reboot-required

    - name: Avviso se il riavvio è necessario
      debug:
        msg: "ATTENZIONE: Il server richiede un riavvio per applicare gli aggiornamenti del kernel."
      when: reboot_required_file.stat.exists | default(false)
      
    - name: "Notifica Telegram"
      delegate_to: localhost
      run_once: true
      vars:
        token: "7746304837:AAEFXj47CX3OgodAwip7AZA1F6glV5AtOhA"
        chat_id: "8012944611"
      shell: |
        curl -s -X POST "https://api.telegram.org/bot{{ token }}/sendMessage" \
             -d chat_id="{{ chat_id }}" \
             -d parse_mode="HTML" \
             -d text="<b>✅ Semaphore Update</b>%0A📦 Aggiornamento completato sui container.%0A🕒 Ora: {{ ansible_date_time.time }}"  
      
