---
- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: "Check connettività (ignora IP vuoti)"
      wait_for_connection:
        timeout: 2
      ignore_unreachable: yes
      register: ssh_check

    - name: "Aggiorna APT (solo se raggiungibile)"
      when: ssh_check is success
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        purge: yes
      ignore_unreachable: yes

    - name: "Controlla se è richiesto un riavvio"
      when: ssh_check is success
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Avviso se il riavvio è necessario"
      when: 
        - ssh_check is success
        - reboot_required_file.stat.exists
      debug:
        msg: "ATTENZIONE: Il server richiede un riavvio per applicare gli aggiornamenti."
