---
- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: "Check connettività"
      wait_for_connection:
        timeout: 2
      ignore_unreachable: yes
      register: ssh_check

    - name: "Aggiorna APT"
      when: ssh_check is success
      apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
        purge: yes
      ignore_unreachable: yes

    - name: "Verifica Reboot"
      when: ssh_check is success
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: "Messaggio Reboot"
      when:
        - ssh_check is success
        - reboot_required_file.stat.exists
      debug:
        msg: "Il server richiede un riavvio."
